window.MEGAPREP_CURRICULUM = {
  SSC: {
    Common: {
      'Bangla 1st Paper': ['গদ্য', 'পদ্য', 'নাটক', 'উপন্যাস', 'সৃজনশীল লেখা', 'ভাব-সম্প্রসারণ'],
      'Bangla 2nd Paper': ['ব্যাকরণ', 'নির্মিতি', 'রচনা', 'সারাংশ', 'চিঠি/দরখাস্ত'],
      'English 1st Paper': ['Seen Passage', 'Unseen Passage', 'Information Transfer', 'Summary', 'Paragraph', 'Story Writing'],
      'English 2nd Paper': ['Grammar', 'Sentence Transformation', 'Completing Sentences', 'CV', 'Formal Letter', 'Essay Writing'],
      Mathematics: ['Algebra', 'Geometry', 'Trigonometry', 'Mensuration', 'Statistics'],
      ICT: ['Digital Devices', 'Number System', 'Web Design', 'Spreadsheet', 'Programming Basics', 'Database & Networking'],
      'Bangladesh and Global Studies': ['History & Heritage', 'Socialization', 'Economy', 'Civics & Governance', 'Geography & Climate'],
      Religion: ['Aqidah', 'Ibadah', 'Akhlaq', 'Quran-Hadith', 'Moral Values'],
      Islam: ['Aqidah', 'Ibadah', 'Akhlaq', 'Quran-Hadith', 'Islamic History'],
      Hinduism: ['Dharma', 'Morality', 'Rituals', 'Scriptures', 'Philosophy'],
      Buddhism: ['Tripitaka', 'Moral Teachings', 'Buddhist History', 'Meditation', 'Ethics'],
      Christianity: ['Bible Studies', 'Life of Jesus', 'Church History', 'Christian Ethics', 'Worship'],
      Science: ['Scientific Process', 'Living World', 'Matter', 'Energy', 'Earth & Space'],
    },
    Science: {
      Physics: ['Physical Quantities & Measurement', 'Motion', 'Force', 'Work Energy Power', 'State of Matter', 'Pressure & Buoyancy', 'Heat', 'Waves & Sound', 'Light', 'Human Eye & Optical Instruments', 'Static Electricity', 'Current Electricity', 'Magnetism', 'Electromagnetism', 'Modern Physics Basics', 'Electronics', 'Renewable Energy'],
      Chemistry: ['Concept of Chemistry', 'States of Matter', 'Structure of Atom', 'Periodic Table', 'Chemical Bond', 'Mole & Chemical Calculations', 'Chemical Reactions', 'Acid-Base-Salt', 'Metals', 'Minerals & Ores', 'Organic Chemistry', 'Hydrocarbons', 'Biochemistry Basics', 'Environmental Chemistry'],
      Biology: ['Cell & Tissue', 'Cell Division', 'Classification', 'Plant Morphology', 'Plant Physiology', 'Animal Physiology', 'Digestion', 'Blood & Circulation', 'Respiration & Excretion', 'Nervous Coordination', 'Reproduction', 'Genetics', 'Evolution', 'Ecology & Environment'],
      'Higher Mathematics': ['Set & Function', 'Algebraic Expressions', 'Geometry', 'Coordinate Geometry', 'Trigonometry', 'Mensuration', 'Statistics', 'Probability', 'Linear Equation', 'Quadratic Equation'],
    },
    Humanities: {
      History: ['Ancient Bengal', 'Sultanate & Mughal', 'British Period', 'Language Movement', 'Liberation War'],
      Geography: ['Physical Geography', 'Climate', 'Population', 'Natural Resources', 'Disaster Management'],
      Civics: ['State & Government', 'Constitution', 'Human Rights', 'Law & Judiciary', 'Citizenship'],
      Economics: ['Basic Concepts', 'Demand Supply', 'National Income', 'Money & Banking', 'Development Economics'],
    },
    Business: {
      Accounting: ['Accounting Concepts', 'Transactions', 'Journal', 'Ledger', 'Trial Balance', 'Financial Statements', 'Depreciation'],
      Finance: ['Business Finance', 'Banking', 'Insurance', 'Capital Market', 'Budgeting'],
      Entrepreneurship: ['Business Concept', 'Entrepreneurship', 'Business Plan', 'Management', 'Marketing', 'Business Environment'],
    },
  },
  HSC: {
    Common: {
      'Bangla 1st Paper': ['কবিতা', 'গদ্য', 'নাটক', 'উপন্যাস', 'সৃজনশীল উত্তর'],
      'Bangla 2nd Paper': ['ব্যাকরণ', 'নির্মিতি', 'রচনা', 'প্রতিবেদন', 'পত্র/দরখাস্ত'],
      'English 1st Paper': ['Reading Skills', 'Information Transfer', 'Summary', 'Flow Chart', 'Paragraph', 'Essay'],
      'English 2nd Paper': ['Grammar', 'Narration', 'Modifiers', 'Sentence Connectors', 'Formal Letter', 'Application'],
      ICT: ['Communication Systems', 'Number System & Logic', 'HTML CSS', 'C Programming', 'Database', 'Networking & Cyber Security'],
      Statistics: ['Data Presentation', 'Measures of Central Tendency', 'Dispersion', 'Probability', 'Correlation & Regression'],
    },
    Science: {
      'Physics 1st Paper': ['Physical World & Measurement', 'Vector', 'Motion in Two Dimensions', 'Newtonian Mechanics', 'Work Energy Power', 'Gravitation & Satellite', 'Properties of Matter', 'Simple Harmonic Motion', 'Wave', 'Ideal Gas & Kinetic Theory'],
      'Physics 2nd Paper': ['Thermodynamics', 'Static Electricity', 'Current Electricity', 'Physical Optics', 'Geometrical Optics', 'Modern Physics', 'Atomic Model & Nuclear Physics', 'Semiconductor & Electronics', 'Communication Systems'],
      Physics: ['Physical World & Measurement', 'Vector', 'Motion in Two Dimensions', 'Newtonian Mechanics', 'Work Energy Power', 'Gravitation & Satellite', 'Properties of Matter', 'Simple Harmonic Motion', 'Wave', 'Ideal Gas & Kinetic Theory', 'Thermodynamics', 'Static Electricity', 'Current Electricity', 'Physical Optics', 'Geometrical Optics', 'Modern Physics', 'Atomic Model & Nuclear Physics', 'Semiconductor & Electronics', 'Communication Systems'],
      'Chemistry 1st Paper': ['Lab Safety & Practical Skills', 'Qualitative Chemistry', 'States of Matter', 'Thermochemistry', 'Chemical Changes', 'Work, Energy & Enthalpy', 'Chemical Equilibrium', 'Ionic Equilibrium', 'Redox Reaction'],
      'Chemistry 2nd Paper': ['Organic Chemistry Basics', 'Hydrocarbons', 'Functional Group Chemistry', 'Alcohol-Phenol-Ether', 'Carbonyl Compounds', 'Carboxylic Acid Derivatives', 'Aromatic Compounds', 'Electrochemistry', 'Acid-Base Chemistry', 'Metallurgy', 'Chemical Industries'],
      Chemistry: ['Lab Safety & Practical Skills', 'Qualitative Chemistry', 'States of Matter', 'Thermochemistry', 'Chemical Changes', 'Work, Energy & Enthalpy', 'Chemical Equilibrium', 'Ionic Equilibrium', 'Redox Reaction', 'Organic Chemistry Basics', 'Hydrocarbons', 'Functional Group Chemistry', 'Alcohol-Phenol-Ether', 'Carbonyl Compounds', 'Carboxylic Acid Derivatives', 'Aromatic Compounds', 'Electrochemistry', 'Acid-Base Chemistry', 'Metallurgy', 'Chemical Industries'],
      'Biology 1st Paper': ['Cell & Cell Division', 'Cell Chemistry', 'Microbiology', 'Algae & Fungi', 'Bryophyta & Pteridophyta', 'Gymnosperm & Angiosperm', 'Plant Anatomy', 'Plant Physiology', 'Plant Reproduction', 'Economic Botany'],
      'Biology 2nd Paper': ['Animal Diversity & Classification', 'Animal Tissue', 'Digestion & Absorption', 'Blood & Circulation', 'Respiration & Excretion', 'Movement & Coordination', 'Human Reproduction', 'Genetics', 'Evolution', 'Biotechnology', 'Ecology & Environment'],
      Biology: ['Cell & Cell Division', 'Cell Chemistry', 'Microbiology', 'Algae & Fungi', 'Bryophyta & Pteridophyta', 'Gymnosperm & Angiosperm', 'Plant Anatomy', 'Plant Physiology', 'Plant Reproduction', 'Economic Botany', 'Animal Diversity & Classification', 'Animal Tissue', 'Digestion & Absorption', 'Blood & Circulation', 'Respiration & Excretion', 'Movement & Coordination', 'Human Reproduction', 'Genetics', 'Evolution', 'Biotechnology', 'Ecology & Environment'],
      'Higher Mathematics 1st Paper': ['Matrix & Determinant', 'Complex Number', 'Straight Line', 'Circle', 'Conic Sections', 'Permutation & Combination', 'Trigonometric Ratio', 'Trigonometric Function & Identity'],
      'Higher Mathematics 2nd Paper': ['Inverse Trigonometric Function', 'Limit & Continuity', 'Differentiation', 'Integration', 'Differential Equation', 'Binomial Expansion', 'Vector', 'Statics', 'Plane Motion', 'Probability'],
      'Higher Mathematics': ['Matrix & Determinant', 'Complex Number', 'Straight Line', 'Circle', 'Conic Sections', 'Permutation & Combination', 'Trigonometric Ratio', 'Trigonometric Function & Identity', 'Inverse Trigonometric Function', 'Limit & Continuity', 'Differentiation', 'Integration', 'Differential Equation', 'Binomial Expansion', 'Vector', 'Statics', 'Plane Motion', 'Probability'],
    },
    Humanities: {
      History: ['Historiography', 'Ancient Civilization', 'Medieval India', 'Colonial Bengal', 'Nationalism', 'Bangladesh Affairs'],
      Logic: ['Terms', 'Propositions', 'Syllogism', 'Deduction', 'Induction', 'Fallacies'],
      Sociology: ['Society', 'Culture', 'Social Institutions', 'Social Change', 'Social Problems'],
      Economics: ['Microeconomics', 'Macroeconomics', 'National Income', 'Public Finance', 'International Trade', 'Development'],
      Geography: ['Geomorphology', 'Climatology', 'Population Geography', 'Urban Geography', 'Resource Management'],
      'Social Work': ['Social Welfare', 'Case Work', 'Group Work', 'Community Development', 'Social Research'],
    },
    Business: {
      Accounting: ['Partnership Accounts', 'Company Accounts', 'Final Accounts', 'Financial Statement Analysis', 'Cost Accounting', 'Working Capital'],
      Finance: ['Financial Management', 'Time Value of Money', 'Capital Budgeting', 'Risk & Return', 'Insurance', 'Banking System'],
      Management: ['Management Thought', 'Planning', 'Organizing', 'Staffing', 'Leadership', 'Controlling'],
      Marketing: ['Marketing Concepts', 'Market Segmentation', 'Consumer Behaviour', 'Product & Pricing', 'Distribution', 'Promotion', 'Digital Marketing'],
      'Production Management': ['Production Process', 'Capacity Planning', 'Inventory Control', 'Quality Management', 'Project Management'],
    },
  },
};
