window.MEGAPREP_CURRICULUM = {
  SSC: {
    Common: {
      'Bangla 1st Paper': ['গদ্য', 'পদ্য', 'নাটক', 'উপন্যাস', 'সৃজনশীল লেখা', 'ভাব-সম্প্রসারণ'],
      'Bangla 2nd Paper': ['ব্যাকরণ', 'নির্মিতি', 'রচনা', 'সারাংশ', 'চিঠি/দরখাস্ত'],
      'English 1st Paper': ['Seen Passage', 'Unseen Passage', 'Information Transfer', 'Summary', 'Paragraph', 'Story Writing'],
      'English 2nd Paper': ['Grammar', 'Sentence Transformation', 'Completing Sentences', 'CV', 'Formal Letter', 'Essay Writing'],
      Mathematics: ['Algebra', 'Geometry', 'Trigonometry', 'Mensuration', 'Statistics'],
      ICT: ['Digital Devices', 'Number System', 'Web Design', 'Spreadsheet', 'Programming Basics', 'Database & Networking'],
      'Bangladesh and Global Studies': ['History & Heritage', 'Socialization', 'Economy', 'Civics & Governance', 'Geography & Climate'],
      Religion: ['Aqidah', 'Ibadah', 'Akhlaq', 'Quran-Hadith', 'Moral Values'],
      Islam: ['Aqidah', 'Ibadah', 'Akhlaq', 'Quran-Hadith', 'Islamic History'],
      Hinduism: ['Dharma', 'Morality', 'Rituals', 'Scriptures', 'Philosophy'],
      Buddhism: ['Tripitaka', 'Moral Teachings', 'Buddhist History', 'Meditation', 'Ethics'],
      Christianity: ['Bible Studies', 'Life of Jesus', 'Church History', 'Christian Ethics', 'Worship'],
      Science: ['Scientific Process', 'Living World', 'Matter', 'Energy', 'Earth & Space'],
    },
    Science: {
      Physics: ['Physical Quantities', 'Measurement & Error', 'Motion', 'Force & Pressure', 'Work Power Energy', 'State of Matter & Pressure', 'Heat & Temperature', 'Wave & Sound', 'Light & Reflection', 'Refraction & Lenses', 'Static Electricity', 'Current Electricity', 'Magnetism', 'Electromagnetism', 'Electronic Components', 'Renewable Energy', 'Modern Physics Intro'],
      Chemistry: ['States of Matter', 'Structure of Atom', 'Periodic Table', 'Chemical Bond', 'Mole Concept', 'Chemical Reaction', 'Acid Base Salt', 'Metals', 'Mineral Resources', 'Organic Chemistry', 'Hydrocarbon', 'Environmental Chemistry'],
      Biology: ['Cell & Tissue', 'Cell Division', 'Classification', 'Plant Physiology', 'Animal Physiology', 'Digestion & Nutrition', 'Respiration & Circulation', 'Reproduction', 'Genetics', 'Heredity & Evolution', 'Environment & Ecosystem'],
      'Higher Mathematics': ['Set & Function', 'Algebra', 'Coordinate Geometry', 'Trigonometry', 'Calculus Basics', 'Probability & Statistics'],
    },
    Humanities: {
      History: ['Ancient Bengal', 'Sultanate & Mughal', 'British Period', 'Language Movement', 'Liberation War'],
      Geography: ['Physical Geography', 'Climate', 'Population', 'Natural Resources', 'Disaster Management'],
      Civics: ['State & Government', 'Constitution', 'Human Rights', 'Law & Judiciary', 'Citizenship'],
      Economics: ['Basic Concepts', 'Demand Supply', 'National Income', 'Money & Banking', 'Development Economics'],
    },
    Business: {
      Accounting: ['Accounting Concepts', 'Transactions', 'Journal', 'Ledger', 'Trial Balance', 'Financial Statements', 'Depreciation'],
      Finance: ['Business Finance', 'Banking', 'Insurance', 'Capital Market', 'Budgeting'],
      Entrepreneurship: ['Business Concept', 'Entrepreneurship', 'Business Plan', 'Management', 'Marketing', 'Business Environment'],
    },
  },
  HSC: {
    Common: {
      'Bangla 1st Paper': ['কবিতা', 'গদ্য', 'নাটক', 'উপন্যাস', 'সৃজনশীল উত্তর'],
      'Bangla 2nd Paper': ['ব্যাকরণ', 'নির্মিতি', 'রচনা', 'প্রতিবেদন', 'পত্র/দরখাস্ত'],
      'English 1st Paper': ['Reading Skills', 'Information Transfer', 'Summary', 'Flow Chart', 'Paragraph', 'Essay'],
      'English 2nd Paper': ['Grammar', 'Narration', 'Modifiers', 'Sentence Connectors', 'Formal Letter', 'Application'],
      ICT: ['Communication Systems', 'Number System & Logic', 'HTML CSS', 'C Programming', 'Database', 'Networking & Cyber Security'],
      Statistics: ['Data Presentation', 'Measures of Central Tendency', 'Dispersion', 'Probability', 'Correlation & Regression'],
    },
    Science: {
      'Physics 1st Paper': ['Physical World & Measurement', 'Vector', 'Dynamics', 'Work Energy Power', 'Gravitation', 'Simple Harmonic Motion', 'Wave'],
      'Physics 2nd Paper': ['Thermodynamics', 'Ideal Gas', 'Electrostatics', 'Current Electricity', 'Modern Physics', 'Semiconductor'],
      'Chemistry 1st Paper': ['Environmental Chemistry', 'Qualitative Chemistry', 'States of Matter', 'Thermochemistry', 'Chemical Equilibrium'],
      'Chemistry 2nd Paper': ['Organic Chemistry', 'Electrochemistry', 'Acids-Bases', 'Metallurgy', 'Chemical Industry'],
      'Biology 1st Paper': ['Cell & Cell Division', 'Microbiology', 'Algae & Fungi', 'Plant Anatomy', 'Plant Physiology'],
      'Biology 2nd Paper': ['Genetics', 'Evolution', 'Human Physiology', 'Biotechnology', 'Ecology & Environment'],
      'Higher Mathematics 1st Paper': ['Matrix & Determinant', 'Complex Number', 'Straight Line', 'Circle', 'Conic Sections', 'Permutation & Combination', 'Trigonometric Ratio', 'Trigonometric Function & Identity'],
      'Higher Mathematics 2nd Paper': ['Inverse Trigonometric Function', 'Limit & Continuity', 'Differentiation', 'Integration', 'Differential Equation', 'Binomial Expansion', 'Vector', 'Statics', 'Plane Motion', 'Probability'],
    },
    Humanities: {
      History: ['Historiography', 'Ancient Civilization', 'Medieval India', 'Colonial Bengal', 'Nationalism', 'Bangladesh Affairs'],
      Logic: ['Terms', 'Propositions', 'Syllogism', 'Deduction', 'Induction', 'Fallacies'],
      Sociology: ['Society', 'Culture', 'Social Institutions', 'Social Change', 'Social Problems'],
      Economics: ['Microeconomics', 'Macroeconomics', 'National Income', 'Public Finance', 'International Trade', 'Development'],
      Geography: ['Geomorphology', 'Climatology', 'Population Geography', 'Urban Geography', 'Resource Management'],
      'Social Work': ['Social Welfare', 'Case Work', 'Group Work', 'Community Development', 'Social Research'],
    },
    Business: {
      Accounting: ['Partnership Accounts', 'Company Accounts', 'Final Accounts', 'Financial Statement Analysis', 'Cost Accounting', 'Working Capital'],
      Finance: ['Financial Management', 'Time Value of Money', 'Capital Budgeting', 'Risk & Return', 'Insurance', 'Banking System'],
      Management: ['Management Thought', 'Planning', 'Organizing', 'Staffing', 'Leadership', 'Controlling'],
      Marketing: ['Marketing Concepts', 'Market Segmentation', 'Consumer Behaviour', 'Product & Pricing', 'Distribution', 'Promotion', 'Digital Marketing'],
      'Production Management': ['Production Process', 'Capacity Planning', 'Inventory Control', 'Quality Management', 'Project Management'],
    },
  },
};
